import { Job } from '../types';

export const mockJobs: Job[] = [
  {
    id: '1',
    title: 'Senior React Native Developer',
    company: 'Spotify',
    location: 'San Martin, Sweden',
    type: 'Full-time',
    workMode: 'Remote',
    salary: '$100K-$150K/Annually',
    experience: '3+ Years',
    description: 'Join our mobile team to build the next generation of music streaming apps. We\'re looking for a passionate React Native developer who loves creating smooth, performant mobile apps.',
    requirements: [
      'React Native',
      'CI / CD',
      'Redux',
      'Mobile Development',
    ],
    tags: ['React Native', 'Redux', 'CI/CD', 'Mobile'],
    postedDate: new Date('2025-01-05'),
  },
  {
    id: '2',
    title: 'Frontend Developer',
    company: 'Klarna',
    location: 'Stockholm, Sweden',
    type: 'Full-time',
    workMode: 'Hybrid',
    salary: '$90K-$130K/Annually',
    experience: '2+ Years',
    description: 'Build beautiful and intuitive user interfaces for our fintech platform. Work with cutting-edge technologies and help millions of users manage their finances.',
    requirements: [
      'React',
      'TypeScript',
      'CSS/SASS',
      'RESTful APIs',
      'Git',
    ],
    tags: ['React', 'TypeScript', 'Frontend'],
    postedDate: new Date('2025-01-08'),
  },
  {
    id: '3',
    title: 'Full Stack Engineer',
    company: 'Stripe',
    location: 'San Francisco, CA',
    type: 'Full-time',
    workMode: 'Remote',
    salary: '$120K-$180K/Annually',
    experience: '4+ Years',
    description: 'Help build the economic infrastructure for the internet. Work on both frontend and backend systems that process billions of dollars.',
    requirements: [
      'React',
      'Node.js',
      'PostgreSQL',
      'AWS',
      'Microservices',
    ],
    tags: ['Full Stack', 'React', 'Node.js'],
    postedDate: new Date('2025-01-07'),
  },
  {
    id: '4',
    title: 'Mobile Developer (iOS/Android)',
    company: 'Uber',
    location: 'San Francisco, CA',
    type: 'Full-time',
    workMode: 'On-site',
    salary: '$110K-$160K/Annually',
    experience: '3+ Years',
    description: 'Build and maintain the Uber mobile app used by millions daily. Focus on performance, reliability, and user experience.',
    requirements: [
      'Swift or Kotlin',
      'React Native',
      'Mobile Architecture',
      'Testing',
    ],
    tags: ['Mobile', 'iOS', 'Android'],
    postedDate: new Date('2025-01-06'),
  },
  {
    id: '5',
    title: 'Backend Engineer',
    company: 'Netflix',
    location: 'Los Gatos, CA',
    type: 'Full-time',
    workMode: 'Hybrid',
    salary: '$130K-$190K/Annually',
    experience: '5+ Years',
    description: 'Build scalable backend systems that serve millions of streaming users worldwide. Work with cutting-edge distributed systems.',
    requirements: [
      'Java or Python',
      'Microservices',
      'AWS',
      'Distributed Systems',
      'SQL/NoSQL',
    ],
    tags: ['Backend', 'Java', 'Microservices'],
    postedDate: new Date('2025-01-04'),
  },
];